version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install dependencies
          command: |
            .circleci/install_dep.sh
      - run:
          name: Builder
          command: |
            rake build -t -v
            cp -R pkg /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - pkg

  unit_test:
    docker:
       - image: circleci/ruby:2.6.1-node-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install dependencies
          command: |
            .circleci/install_dep.sh
      - run:
          name: Run unit tests
          command: |
            bundle exec rake test -t -v

  func_test_master:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: trigger
          command: |
            .circleci/trigger_func_test.sh master

  func_test_develop:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: trigger
          command: |
            .circleci/trigger_func_test.sh develop

workflows:
  version: 2
  build_test_push:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - /^release\/.*/
                - master
      - unit_test:
          requires:
            - build
      - func_test_master:
          requires:
            - unit_test
      - func_test_develop:
          requires:
            - unit_test